# This workflow will upload a Python Package using Twine when a release is created
# See https://scikit-hep.org/developer/gha_pure

name: Upload Python Package

on:
  push:
    paths:
      - 'z4d_certified_devices/version.py'

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build SDist and wheel
      run: pipx run build

    - uses: actions/upload-artifact
      with:
        path: dist/*

    - name: Check metadata
      run: pipx run twine check dist/*

  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    #if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/download-artifact
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true
